### PR TITLE
Fixed Issue #54  https://github.com/Backendless/JS-SDK/issues/54  htt…

### PR DESCRIPTION
**Pull request by rizemesh**
Fixed this issue http://support.backendless.com/topic/upload-file-problem-uncaught-object-put-httplocalhost8000undefined

I fixed in this way.

First I use a closure on line 3576 to maintain both event from onloadend and from the reader:

```
reader.onloadend = (function(f) {
return function(e){
sendEncoded(e,f);
}
})(reader);
```

Then I adapted the sendEncoded method on line 3432 whit this code:

```
function sendEncoded(e1, e2) {
var xhr = new XMLHttpRequest(),
boundary = '-backendless-multipart-form-boundary-' + getNow(),
badResponse = function(xhr) {
var result = {};
try {
result = JSON.parse(xhr.responseText);
} catch (e) {
result.message = xhr.responseText;
}
result.statusCode = xhr.status;
return result;
};
xhr.open("PUT", e2.uploadPath, true);
xhr.setRequestHeader('Content-Type', 'text/plain');
xhr.setRequestHeader('application-id', Backendless.applicationId);
xhr.setRequestHeader("secret-key", Backendless.secretKey);
xhr.setRequestHeader("application-type", "JS");
if ((currentUser != null && currentUser["user-token"])) {
xhr.setRequestHeader("user-token", currentUser["user-token"]);
} else if (Backendless.LocalCache.exists("user-token")) {
xhr.setRequestHeader("user-token", Backendless.LocalCache.get("user-token"));
}
if (UIState !== null) {
xhr.setRequestHeader("uiState", UIState);
}
var asyncHandler = e2.asyncHandler;
if (asyncHandler) {
xhr.onreadystatechange = function() {
if (xhr.readyState == 4) {
if (xhr.status >= 200 && xhr.status < 300) {
asyncHandler.success(JSON.parse(xhr.responseText));
} else {
asyncHandler.fault(JSON.parse(xhr.responseText));
}
}
};
}
xhr.send(e1.target.result.split(',')[1]);
if (asyncHandler) {
return xhr;
}
if (xhr.status >= 200 && xhr.status < 300) {
return xhr.responseText ? JSON.parse(xhr.responseText) : true;
} else {
throw badResponse(xhr);
}
}
```

### CODE REVIEW

**Comment by vengrov** [comment]
Please update your branch to latest master. This MR reverts recent changes

**Comment by vengrov** [comment]
Depending on arguments passed into `Backendless.Files.saveFile` method, this operation could be synchronous or asynchronous. 
The issue you encounter, is that we always use asynchronous way in `sendEncoded` method.
This is properly fixed in #57 
Thanks for contribution!

**Comment by rizemesh** [comment]
It does not resolve because the problem is the same.
On line 3448 "this.uploadPath" is always undefined

to prove this I put a console.log(this); on line 3447 and how you can see on the screenshot the THIS object does not have any uploadPath or asyncHandler


schermata da 2016-11-22 11-02-43

**Comment by illyaV** [comment]
I've answered in your topic on the support forum  
http://support.backendless.com/topic/upload-file-problem-uncaught-object-put-httplocalhost8000undefined#comment-24885

**Comment by rizemesh** [comment]
If someone has the same problem I created a fork of the cordova plugin including the fix for backendless.

This is the repository

https://github.com/rizemesh/cordova-plugin-file

**Pull request closed without merging**
