### PR TITLE
Send email response

### PR DESCRIPTION
**Pull request by stanislav-grin**
`sendEmail` method should return Message status instead of object.

### CODE REVIEW

**Comment by mkrajcir** [comment]
`sendEmail` return status `SCHEDULED` and I am not able to find status in case message is not delivered. So I would like to get also `Message ID` to find status via another API.

**Comment by mkrajcir** [comment]
@stanislav-grin please reopen this issue according to issue of missing message ID during investigating problem https://support.backendless.com/t/email-settings-password-missing/12412/30

**Comment by stanislav-grin** [comment]
Hi @mkrajcir ,

thanks for reporting this issue. I have fixed this in this PR https://github.com/Backendless/JS-SDK/pull/195

And made a new release v6.2.4 (also published to the npm). 
Please update the version of SDK and let us know if this solves your issue.

Thanks!

**Comment by mkrajcir** [comment]
@stanislav-grin yes, it works! Thanks

**Pull request merged**
